var hierarchy =
[
    [ "Animator", "class_animator.html", null ],
    [ "AnimatorInfo", "class_animator_info.html", null ],
    [ "AnimCondition", "struct_anim_condition.html", null ],
    [ "AnimState", "struct_anim_state.html", null ],
    [ "AnimStateMachine", "class_anim_state_machine.html", null ],
    [ "Background", "class_background.html", null ],
    [ "BacklogData", "struct_backlog_data.html", null ],
    [ "BaseButton", "class_base_button.html", [
      [ "MenuButton", "class_menu_button.html", null ],
      [ "SettingsButton", "class_settings_button.html", null ]
    ] ],
    [ "Camera", "class_camera.html", null ],
    [ "Color", "struct_color.html", null ],
    [ "CutsceneCommands", "class_cutscene_commands.html", null ],
    [ "CutsceneManager", "class_cutscene_manager.html", null ],
    [ "Editor", "class_editor.html", null ],
    [ "EditorButton", "class_editor_button.html", null ],
    [ "Entity", "class_entity.html", [
      [ "BackgroundLayer", "class_background_layer.html", null ],
      [ "Block", "class_block.html", null ],
      [ "Bug", "class_bug.html", null ],
      [ "CutsceneTrigger", "class_cutscene_trigger.html", null ],
      [ "Door", "class_door.html", null ],
      [ "Ether", "class_ether.html", null ],
      [ "Goal", "class_goal.html", null ],
      [ "Ladder", "class_ladder.html", null ],
      [ "Missile", "class_missile.html", null ],
      [ "NPC", "class_n_p_c.html", null ],
      [ "Path", "class_path.html", null ],
      [ "Platform", "class_platform.html", null ],
      [ "Player", "class_player.html", null ],
      [ "Shroom", "class_shroom.html", null ],
      [ "Text", "class_text.html", null ],
      [ "Tile", "class_tile.html", null ]
    ] ],
    [ "FontInfo", "struct_font_info.html", null ],
    [ "FuncLUT", "struct_func_l_u_t.html", null ],
    [ "Game", "class_game.html", null ],
    [ "Glyph", "struct_glyph.html", null ],
    [ "GlyphHashFunction", "class_glyph_hash_function.html", null ],
    [ "GlyphSurfaceData", "struct_glyph_surface_data.html", null ],
    [ "ImageDeleter", "struct_image_deleter.html", null ],
    [ "Logger", "class_logger.html", null ],
    [ "MenuScreen", "class_menu_screen.html", null ],
    [ "Mesh", "class_mesh.html", null ],
    [ "PathNode", "class_path_node.html", null ],
    [ "Physics", "class_physics.html", null ],
    [ "PhysicsInfo", "class_physics_info.html", null ],
    [ "Property", "class_property.html", null ],
    [ "Renderer", "class_renderer.html", null ],
    [ "SceneData", "struct_scene_data.html", null ],
    [ "SceneLabel", "class_scene_label.html", null ],
    [ "SceneLine", "class_scene_line.html", null ],
    [ "ShaderProgram", "class_shader_program.html", null ],
    [ "Sound", "struct_sound.html", null ],
    [ "SoundChannel", "struct_sound_channel.html", null ],
    [ "SoundManager", "class_sound_manager.html", null ],
    [ "Spell", "class_spell.html", [
      [ "SpellPop", "class_spell_pop.html", null ],
      [ "SpellPush", "class_spell_push.html", null ]
    ] ],
    [ "Sprite", "class_sprite.html", null ],
    [ "SpriteManager", "class_sprite_manager.html", null ],
    [ "Test", "class_test.html", null ],
    [ "Textbox", "class_textbox.html", null ],
    [ "TextTag", "struct_text_tag.html", null ],
    [ "Texture", "class_texture.html", null ],
    [ "Timer", "class_timer.html", null ],
    [ "UserDefinedFunction", "struct_user_defined_function.html", null ],
    [ "Vector2", "class_vector2.html", null ]
];